// Description: Common TCP ports and their corresponding service names.
// generated by Gemini, 2025

// Structure to hold port and service name
struct CommonPort {
    int port;
    const char *service;
};

// Array of common TCP ports
struct CommonPort common_tcp_ports[] = {
    {21, "ftp"},    
    {23, "telnet"},
    {25, "smtp"},
    {53, "dns"},  // Both TCP and UDP, but often TCP for zone transfers
    {80, "http"},
    {110, "pop3"},
    {139, "netbios-ssn"}, // SMB over TCP
    {143, "imap"},
    {443, "https"},
    {445, "microsoft-ds"}, // SMB over TCP (newer)
    {3306, "mysql"},
    {8080, "http-proxy"}, // Alternate HTTP port
    {8443, "https-alt"}, // Alternate HTTPS port
    {27017, "mongodb"},  // MongoDB default port
    {6379, "redis"},    // Redis default port
    {5432, "postgresql"}, // PostgreSQL default port
    {1521, "oracle"},    // Oracle default port
    {3389, "rdp"},       // Remote Desktop Protocol
    {25565, "minecraft"}, // Minecraft server (default)
     {2181, "zookeeper"}, // ZooKeeper
     {9042, "cassandra"}, // Cassandra
     {9200, "elasticsearch"}, // Elasticsearch
     {5601, "kibana"}, // Kibana
    {0, NULL} // Sentinel value to mark the end of the array
};